[package]
name = "halo2_extr"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = { version = "0.6", default-features = false }
ff = "0.13"
plotters = { version = "0.3.0", default-features = false }
plotters-bitmap = { version = "0.3.2", features = ["image"] }
halo2 = { path = "../source/halo2/halo2/" }
halo2_proofs = { path = "../source/halo2/halo2_proofs/", features = ["dev-graph", "test-dev-graph"] }
arrayvec = { version = "0.7.2" }
regex = "1"
subtle = { version = "2.5.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }